# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push to Testflight"
  lane :beta do # change beta to whatever you want to name this lane. Currently, you need to do fastlane beta to invoke this
    get_certificates         
    get_provisioning_profile 
    increment_build_number
    build_app
    upload_to_testflight
  end
end
